apiVersion: apps/v1
kind: Deployment
metadata:
   name: cta-monitoring
   labels:
     app: cta-monitoring
spec:
   replicas: 1
   selector:
     matchLabels:
       app: cta-monitoring
   template:
      metadata:
        labels:
          app: cta-monitoring
      spec:
        containers:
        - name: cta-monitoring-container01
          image: imageregistry.fnal.gov/cta/cta-fluentd:v1.16 #imageregistry.fnal.gov/cta/ctafluentd:latest #localhost/cta/ctafluentd:typecast #imageregistry.fnal.gov/cta/ctafluentd:latest
          #command: [ "/bin/bash", "-c", "--" ]
          #          #command: ["/usr/sbin/td-agent", "-c", "/etc/td-agent/td-agent.conf"]
          volumeMounts:
          - name: td-agent-config
            mountPath: /etc/td-agent/
          - name: ctafrontendforwardableclientsss
            mountPath: /etc-host/
          - name: ctamessages
            mountPath: /var/host-logs/cta/
            readOnly: true
          env:
          - name: CTA_INSTANCE
            valueFrom:
              secretKeyRef:
                key: CTA_INSTANCE
                name: cta-secrets
        volumes:
        - name: td-agent-config
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            #              # to add to the container
            name: tapedfluentdconfig  #tapedfluentddeploymentjan2024grafana
        - name: ctamessages
          hostPath:
            path: /minikubeVM/var/host-logs/cta/
            #type: File
        - name: ctafrontendforwardableclientsss
          secret:
            secretName: ctafrontendforwardableclientsss
            #secretName: eos-sss
