FROM almalinux/9-base

RUN dnf upgrade -y \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install 'dnf-command(config-manager)'\
    && dnf clean all \
    && rm -rf /var/cache/dnf
RUN dnf config-manager --set-enabled crb

RUN dnf install -y unzip epel-release \
    && dnf clean all \
    && rm -rf /var/cache/dnf

# Using test repo to get 5.10.11 with tape type
ADD cta-public-5-alma9.repo  /etc/yum.repos.d/
#ADD cta-public-5-test-alma9.repo  /etc/yum.repos.d/

RUN yum -y install cta-cli \
    && yum clean all \
    && rm -rf /var/cache/yum

# Install cloudprober
ADD https://github.com/cloudprober/cloudprober/releases/download/v0.13.1/cloudprober-v0.13.1-linux-x86_64.zip /tmp
RUN cd /tmp; unzip cloudprober-v*.zip
RUN cp /tmp/cloudprober-v*/cloudprober /usr/local/bin/cloudprober

# Install probe code
RUN mkdir /python-probes
ADD cta_admin_dr_ls.py /python-probes
ADD cta_admin_tapepool_ls.py /python-probes
ADD cta_admin_tape_ls.py /python-probes
ADD cta_admin_failedrequest_ls.py /python-probes
ADD cta_admin_repack_ls.py /python-probes
ADD common.py /python-probes

RUN mkdir /etc/cta-nobody/
RUN chmod 777 /etc/cta-nobody/

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
