FROM almalinux/9-base
ADD cta-public-5-alma9.repo  /etc/yum.repos.d/
#ADD cta-public-5-test-alma9.repo  /etc/yum.repos.d/
ADD ceph.repo  /etc/yum.repos.d/

RUN dnf upgrade -y \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install 'dnf-command(config-manager)'\
    && dnf clean all \
    && rm -rf /var/cache/dnf
RUN dnf config-manager --set-enabled crb

RUN dnf -y install https://download.oracle.com/otn_software/linux/instantclient/2380000/oracle-instantclient-basic-23.8.0.25.04-1.el9.x86_64.rpm


RUN dnf install -y epel-release \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf install -y epel-release libpq-devel gcc \
                   cta-frontend cta-frontend-grpc cta-lib \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN chmod 777 /var/log/cta
RUN mkdir /etc/cta-nobody/
RUN chmod 777 /etc/cta-nobody/

ADD entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
