#! /usr/bin/env python3

import json
import subprocess

# Get existing storage classes and tape pools

command = subprocess.run(args=["cta-admin", "--json", "sc", "ls"],  capture_output=True, check=True)
existing_scs = json.loads(command.stdout)
sc_names = [sc['name'] for sc in existing_scs]

command = subprocess.run(args=["cta-admin", "--json", "tp", "ls"],  capture_output=True, check=True)
existing_tps = json.loads(command.stdout)
tp_names = [tp['name'] for tp in existing_tps]

# FIXME: Replace this with fetch(es) from Git
with open('/sc-config/tape-pools.json') as json_file:
    description = json.load(json_file)

    for item in description:
        vo = item['vo']
        tape_pools = item['tape_pools']

        for tape_pool in tape_pools:
            copies = tape_pool.get('copies', 1)
            name = tape_pool['name']
            n_tapes = tape_pool['tape_width']
            supply = tape_pool['supply']
            sc_name = f"{vo}.{name}@cta"
            tp_name = f"{vo}.{name}"

            if copies != 1:
                # FIXME: Handle the case where copies = 2
                raise NotImplementedError

            if sc_name in sc_names:
                sc_existed = True
            else:
                # FIXME: Handle the case where it doesn't exist
                pass  # raise NotImplementedError

            if tp_name in tp_names:
                tp_existed = True
            else:
                # FIXME: Handle the case where it doesn't exist
                pass  # raise NotImplementedError

            if tp_existed:
                for tp in existing_tps:
                    if tp['name'] == tp_name:
                        if int(tp['numPartialTapes']) != n_tapes:
                            print(f"numPartialTapes {tp['numPartialTapes']} for {tp_name} should be {n_tapes}")
                            # FIXME: Python API is coming at some point, will need to be adapted
                            subprocess.run(args=["cta-admin", "tp", "ch",
                                                 "-n", tp_name,
                                                 "-p", f"{n_tapes}"],
                                           check=True)
                        if tp['supply'] != n_tapes:
                            print(f"Supply for {tp_name} should be {supply[0]}")
                            # FIXME: Python API is coming at some point, will need to be adapted
                            subprocess.run(args=["cta-admin", "tp", "ch",
                                                 "-n", tp_name,
                                                 "-s", supply[0]],
                                           check=True)

            # FIXME: Check and/or set ArchiveRoutes
