# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cta_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cta_common.proto',
  package='cta.common',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63ta_common.proto\x12\ncta.common\"\"\n\x05\x43lock\x12\x0b\n\x03sec\x18\x01 \x01(\x04\x12\x0c\n\x04nsec\x18\x02 \x01(\x04\"\xd8\x01\n\x0c\x43hecksumBlob\x12-\n\x02\x63s\x18\x01 \x03(\x0b\x32!.cta.common.ChecksumBlob.Checksum\x1a\x98\x01\n\x08\x43hecksum\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32&.cta.common.ChecksumBlob.Checksum.Type\x12\r\n\x05value\x18\x02 \x01(\x0c\"G\n\x04Type\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07\x41\x44LER32\x10\x01\x12\t\n\x05\x43RC32\x10\x02\x12\n\n\x06\x43RC32C\x10\x03\x12\x07\n\x03MD5\x10\x04\x12\x08\n\x04SHA1\x10\x05\"$\n\x07Service\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"2\n\x0bRequesterId\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tgroupname\x18\x02 \x01(\t\"#\n\x07OwnerId\x12\x0b\n\x03uid\x18\x03 \x01(\r\x12\x0b\n\x03gid\x18\x04 \x01(\r\"O\n\x08Security\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0b\n\x03\x61pp\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04prot\x18\x04 \x01(\t\x12\x0c\n\x04grps\x18\x05 \x01(\t\"C\n\x0c\x44iskFileInfo\x12\x0c\n\x04path\x18\x03 \x01(\t\x12%\n\x08owner_id\x18\x04 \x01(\x0b\x32\x13.cta.common.OwnerId\"\xd2\x01\n\x0b\x41rchiveFile\x12\x12\n\narchive_id\x18\x01 \x01(\x04\x12\x15\n\rdisk_instance\x18\x02 \x01(\t\x12\x0f\n\x07\x64isk_id\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\x04\x12\x15\n\rstorage_class\x18\x06 \x01(\t\x12$\n\x02\x64\x66\x18\x07 \x01(\x0b\x32\x18.cta.common.DiskFileInfo\x12\x15\n\rcreation_time\x18\x08 \x01(\x04\x12%\n\x03\x63sb\x18\t \x01(\x0b\x32\x18.cta.common.ChecksumBlob\"8\n\x08TapeFile\x12\x0b\n\x03vid\x18\x01 \x01(\t\x12\r\n\x05\x66_seq\x18\x02 \x01(\x04\x12\x10\n\x08\x62lock_id\x18\x03 \x01(\x04\"8\n\x08\x45ntryLog\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x04\"&\n\x07TapeLog\x12\r\n\x05\x64rive\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x04\x62\x06proto3')
)



_CHECKSUMBLOB_CHECKSUM_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='cta.common.ChecksumBlob.Checksum.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADLER32', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRC32', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRC32C', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MD5', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA1', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=214,
  serialized_end=285,
)
_sym_db.RegisterEnumDescriptor(_CHECKSUMBLOB_CHECKSUM_TYPE)


_CLOCK = _descriptor.Descriptor(
  name='Clock',
  full_name='cta.common.Clock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sec', full_name='cta.common.Clock.sec', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nsec', full_name='cta.common.Clock.nsec', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=66,
)


_CHECKSUMBLOB_CHECKSUM = _descriptor.Descriptor(
  name='Checksum',
  full_name='cta.common.ChecksumBlob.Checksum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='cta.common.ChecksumBlob.Checksum.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='cta.common.ChecksumBlob.Checksum.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHECKSUMBLOB_CHECKSUM_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=285,
)

_CHECKSUMBLOB = _descriptor.Descriptor(
  name='ChecksumBlob',
  full_name='cta.common.ChecksumBlob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cs', full_name='cta.common.ChecksumBlob.cs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CHECKSUMBLOB_CHECKSUM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=285,
)


_SERVICE = _descriptor.Descriptor(
  name='Service',
  full_name='cta.common.Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cta.common.Service.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='cta.common.Service.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=323,
)


_REQUESTERID = _descriptor.Descriptor(
  name='RequesterId',
  full_name='cta.common.RequesterId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='cta.common.RequesterId.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='groupname', full_name='cta.common.RequesterId.groupname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=375,
)


_OWNERID = _descriptor.Descriptor(
  name='OwnerId',
  full_name='cta.common.OwnerId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='cta.common.OwnerId.uid', index=0,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gid', full_name='cta.common.OwnerId.gid', index=1,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=412,
)


_SECURITY = _descriptor.Descriptor(
  name='Security',
  full_name='cta.common.Security',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='cta.common.Security.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app', full_name='cta.common.Security.app', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='cta.common.Security.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prot', full_name='cta.common.Security.prot', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grps', full_name='cta.common.Security.grps', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=493,
)


_DISKFILEINFO = _descriptor.Descriptor(
  name='DiskFileInfo',
  full_name='cta.common.DiskFileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='cta.common.DiskFileInfo.path', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='cta.common.DiskFileInfo.owner_id', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=562,
)


_ARCHIVEFILE = _descriptor.Descriptor(
  name='ArchiveFile',
  full_name='cta.common.ArchiveFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='archive_id', full_name='cta.common.ArchiveFile.archive_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disk_instance', full_name='cta.common.ArchiveFile.disk_instance', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disk_id', full_name='cta.common.ArchiveFile.disk_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='cta.common.ArchiveFile.size', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='storage_class', full_name='cta.common.ArchiveFile.storage_class', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='df', full_name='cta.common.ArchiveFile.df', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='cta.common.ArchiveFile.creation_time', index=6,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='csb', full_name='cta.common.ArchiveFile.csb', index=7,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=775,
)


_TAPEFILE = _descriptor.Descriptor(
  name='TapeFile',
  full_name='cta.common.TapeFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vid', full_name='cta.common.TapeFile.vid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f_seq', full_name='cta.common.TapeFile.f_seq', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='block_id', full_name='cta.common.TapeFile.block_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=777,
  serialized_end=833,
)


_ENTRYLOG = _descriptor.Descriptor(
  name='EntryLog',
  full_name='cta.common.EntryLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='cta.common.EntryLog.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host', full_name='cta.common.EntryLog.host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='cta.common.EntryLog.time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=835,
  serialized_end=891,
)


_TAPELOG = _descriptor.Descriptor(
  name='TapeLog',
  full_name='cta.common.TapeLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='drive', full_name='cta.common.TapeLog.drive', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='cta.common.TapeLog.time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=893,
  serialized_end=931,
)

_CHECKSUMBLOB_CHECKSUM.fields_by_name['type'].enum_type = _CHECKSUMBLOB_CHECKSUM_TYPE
_CHECKSUMBLOB_CHECKSUM.containing_type = _CHECKSUMBLOB
_CHECKSUMBLOB_CHECKSUM_TYPE.containing_type = _CHECKSUMBLOB_CHECKSUM
_CHECKSUMBLOB.fields_by_name['cs'].message_type = _CHECKSUMBLOB_CHECKSUM
_DISKFILEINFO.fields_by_name['owner_id'].message_type = _OWNERID
_ARCHIVEFILE.fields_by_name['df'].message_type = _DISKFILEINFO
_ARCHIVEFILE.fields_by_name['csb'].message_type = _CHECKSUMBLOB
DESCRIPTOR.message_types_by_name['Clock'] = _CLOCK
DESCRIPTOR.message_types_by_name['ChecksumBlob'] = _CHECKSUMBLOB
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE
DESCRIPTOR.message_types_by_name['RequesterId'] = _REQUESTERID
DESCRIPTOR.message_types_by_name['OwnerId'] = _OWNERID
DESCRIPTOR.message_types_by_name['Security'] = _SECURITY
DESCRIPTOR.message_types_by_name['DiskFileInfo'] = _DISKFILEINFO
DESCRIPTOR.message_types_by_name['ArchiveFile'] = _ARCHIVEFILE
DESCRIPTOR.message_types_by_name['TapeFile'] = _TAPEFILE
DESCRIPTOR.message_types_by_name['EntryLog'] = _ENTRYLOG
DESCRIPTOR.message_types_by_name['TapeLog'] = _TAPELOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Clock = _reflection.GeneratedProtocolMessageType('Clock', (_message.Message,), dict(
  DESCRIPTOR = _CLOCK,
  __module__ = 'cta_common_pb2'
  # @@protoc_insertion_point(class_scope:cta.common.Clock)
  ))
_sym_db.RegisterMessage(Clock)

ChecksumBlob = _reflection.GeneratedProtocolMessageType('ChecksumBlob', (_message.Message,), dict(

  Checksum = _reflection.GeneratedProtocolMessageType('Checksum', (_message.Message,), dict(
    DESCRIPTOR = _CHECKSUMBLOB_CHECKSUM,
    __module__ = 'cta_common_pb2'
    # @@protoc_insertion_point(class_scope:cta.common.ChecksumBlob.Checksum)
    ))
  ,
  DESCRIPTOR = _CHECKSUMBLOB,
  __module__ = 'cta_common_pb2'
  # @@protoc_insertion_point(class_scope:cta.common.ChecksumBlob)
  ))
_sym_db.RegisterMessage(ChecksumBlob)
_sym_db.RegisterMessage(ChecksumBlob.Checksum)

Service = _reflection.GeneratedProtocolMessageType('Service', (_message.Message,), dict(
  DESCRIPTOR = _SERVICE,
  __module__ = 'cta_common_pb2'
  # @@protoc_insertion_point(class_scope:cta.common.Service)
  ))
_sym_db.RegisterMessage(Service)

RequesterId = _reflection.GeneratedProtocolMessageType('RequesterId', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTERID,
  __module__ = 'cta_common_pb2'
  # @@protoc_insertion_point(class_scope:cta.common.RequesterId)
  ))
_sym_db.RegisterMessage(RequesterId)

OwnerId = _reflection.GeneratedProtocolMessageType('OwnerId', (_message.Message,), dict(
  DESCRIPTOR = _OWNERID,
  __module__ = 'cta_common_pb2'
  # @@protoc_insertion_point(class_scope:cta.common.OwnerId)
  ))
_sym_db.RegisterMessage(OwnerId)

Security = _reflection.GeneratedProtocolMessageType('Security', (_message.Message,), dict(
  DESCRIPTOR = _SECURITY,
  __module__ = 'cta_common_pb2'
  # @@protoc_insertion_point(class_scope:cta.common.Security)
  ))
_sym_db.RegisterMessage(Security)

DiskFileInfo = _reflection.GeneratedProtocolMessageType('DiskFileInfo', (_message.Message,), dict(
  DESCRIPTOR = _DISKFILEINFO,
  __module__ = 'cta_common_pb2'
  # @@protoc_insertion_point(class_scope:cta.common.DiskFileInfo)
  ))
_sym_db.RegisterMessage(DiskFileInfo)

ArchiveFile = _reflection.GeneratedProtocolMessageType('ArchiveFile', (_message.Message,), dict(
  DESCRIPTOR = _ARCHIVEFILE,
  __module__ = 'cta_common_pb2'
  # @@protoc_insertion_point(class_scope:cta.common.ArchiveFile)
  ))
_sym_db.RegisterMessage(ArchiveFile)

TapeFile = _reflection.GeneratedProtocolMessageType('TapeFile', (_message.Message,), dict(
  DESCRIPTOR = _TAPEFILE,
  __module__ = 'cta_common_pb2'
  # @@protoc_insertion_point(class_scope:cta.common.TapeFile)
  ))
_sym_db.RegisterMessage(TapeFile)

EntryLog = _reflection.GeneratedProtocolMessageType('EntryLog', (_message.Message,), dict(
  DESCRIPTOR = _ENTRYLOG,
  __module__ = 'cta_common_pb2'
  # @@protoc_insertion_point(class_scope:cta.common.EntryLog)
  ))
_sym_db.RegisterMessage(EntryLog)

TapeLog = _reflection.GeneratedProtocolMessageType('TapeLog', (_message.Message,), dict(
  DESCRIPTOR = _TAPELOG,
  __module__ = 'cta_common_pb2'
  # @@protoc_insertion_point(class_scope:cta.common.TapeLog)
  ))
_sym_db.RegisterMessage(TapeLog)


# @@protoc_insertion_point(module_scope)
